#! /usr/bin/env python

import sys

def main(): 
    #
    # Imports
    #
    import metadata
    import time
    from seqdata import BarcodeClusterer
    
    #
    # check input and get commandline args
    #
    try:
	analysisfolder = metadata.AnalysisFolder(sys.argv[1])
    except IndexError: sys.stderr.write('please supply a commandline on format:\analyseClusters <analysis-output-folder>\n');sys.exit()
    
    #
    # check analysis folder
    #
    if not analysisfolder.checkIntegrity() == 'PASS': print analysisfolder.checkIntegrity()+'\nERROR: Now exiting'

    #
    # create a logfile
    #
    logfile = open(analysisfolder.logpath+'/'+time.strftime("%y%m%d-%H:%M:%S",time.localtime())+'_analyseClusters.log.txt','w',1)
    logfile.write('cmd: '+' '.join(sys.argv)+'\n')
    analysisfolder.logfile = logfile

    #
    # restructuring the data
    #
    if not analysisfolder.database.datadropped:
	logfile.write('Restructuring database ... \n')
	barcodeClusterer = BarcodeClusterer(analysisfolder)
	barcodeClusterer.fillReadsDb()
	logfile.write('Dropping data ... \n')
	analysisfolder.database.dropReadColumns()
	logfile.write('done. \n')
    
    logfile.write('analyseClusters FINISHED\n')

if __name__ == "__main__": main()