#! /usr/bin/env python

import sys

def main(): 
    #
    # Imports
    #
    import metadata
    import time
    from seqdata import BarcodeClusterer
    
    #
    # check input and get commandline args
    #
    try:
	analysisfolder = metadata.AnalysisFolder(sys.argv[1])
    except IndexError: sys.stderr.write('please supply a commandline on format:\nbarcodeClusterer <analysis-output-folder>\n');sys.exit()
    
    #
    # check analysis folder
    #
    if not analysisfolder.checkIntegrity() == 'PASS': print analysisfolder.checkIntegrity()+'\nERROR: Now exiting'

    #
    # create a logfile
    #
    logfile = open(analysisfolder.logpath+'/'+time.strftime("%y%m%d-%H:%M:%S",time.localtime())+'_barcodeClusterer','w',1)
    logfile.write('cmd: '+' '.join(sys.argv)+'\n')
    analysisfolder.logfile = logfile

    #
    # cluster barcode sequences
    #
    barcodeClusterer = BarcodeClusterer(analysisfolder)
    barcodeClusterer.clusterBarcodeSequences()
    
    logfile.write('barcodeClusterer FINISHED\n')

if __name__ == "__main__": main()