H770  = 'GGAGCCATTAAGTCGTAGCT'
H1691 = 'GACAGTTCCAAGAGGTCATG'
H4328 = 'TAGGACCAGCGTCTCAGTAT'
ILLI5 = 'AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT'
ILLI7 = 'AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG'

